### ISSUE TITLE
Enhancement: tag auto-generated pull requests

### ISSUE THREAD

**Issue by xeji** [ryantm/nix-update#25]
It would be great to have the tool label the generated pull requests  as "auto" or similar (in a nice color of course :-)   Helps browse and filter the growing list of pull requests.

**Comment by ryantm** [comment]
As a non nixpkgs maintainer, I don't think I'm allowed to add tags.

**Comment by matthewbauer** [comment]
One alternative would be to create an “ryantmofborg” GitHub like GrahamC did and use its token for PRs. You could filter by user.

**Comment by ryantm** [comment]
Is there a way to search PRs for NOT some author?

**Comment by xeji** [comment]
`is:pr is:open -author:xxx` works, same for labels.
A dedicated github account works assuming it's the only one.  
A label would allow for different accounts to submit auto-generated PRs - we might have multiple PR bots doing different things in the future ...
If a label cannot be added via the API, ofborg could do that during checks.

**Comment by matthewbauer** [comment]
Yeah. We could also use GitHub's team feature. Adding a "robots" team would let you add a filter like "is:pr is:open -team:NixOS/robots".

Anyway @ryantm you should email Eelco and explain your use case with adding bot labels. He can probably set you up with Nixpkgs commit rights.

**Comment by xeji** [comment]
On second thought, running a PR bot with commit rights increases risk in case of bugs. It might be safer to use a separate unprivileged bot account and let grahamcofborg add a label if the PR is from a known bot account.

**Comment by ryantm** [comment]
I am now running nix-update as GitHub user @r-ryantm

**Comment by xeji** [comment]
Thanks! Let's consider labeling by grahamcofborg later when another PR bot comes alive.
