### ISSUE TITLE
Every maintainer now has a Github handle!

### ISSUE THREAD

**Issue by Profpatsch** [ryantm/nix-update#4]
With https://github.com/NixOS/nixpkgs/pull/36119 closed, the [`maintainers.nix`](https://github.com/NixOS/nixpkgs/blob/6f7069dab6370b4153c2ff63565dba3d4391d6ba/lib/maintainers-list.nix) now contains a complete set of github handles for (nearly) each maintainer. They are checked to be correct (see PR). Attention, some maintainers don’t have a github field.

**Comment by ryantm** [comment]
Not quite yet on master!

**Comment by ryantm** [comment]
Thanks! Using this now!
